name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/gradle-build-action@v2
        name: Generate code
        with:
          arguments: compileKotlinJs -PenableKsp=true

      - uses: gradle/gradle-build-action@v2
        name: Check - unit tests & code style
        with:
          arguments: check jsBrowserProductionLibraryDistribution

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run integration tests
        id: integration-test
        run: |
          cd samples
          ./setupNpm.sh
          body=$(./_run.sh)
          body="${body//$'\n'/%0A}"
          echo "::set-output name=body::$body"
          cd -

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          header: integration tests
          message: ${{ steps.integration-test.outputs.body }}
